const foodItems = [
  {
    id: 1,
    name: "Cheese Burst Pizza",
    price: 299,
    discountPrice: 249,
    description: "Delicious cheesy burst pizza with extra toppings.",
    ratings: 4.5,
    ratingsCount: 120,
    type: "veg",
    cuisines: ["Italian", "Fast Food"],
    category: "Fast Food",
  },
  {
    id: 2,
    name: "Chicken Biryani",
    price: 349,
    discountPrice: 299,
    description: "Aromatic and flavorful biryani with tender chicken pieces.",
    ratings: 4.7,
    ratingsCount: 200,
    type: "non-veg",
    cuisines: ["Indian", "Mughlai"],
    category: "South Indian",
  },
  {
    id: 3,
    name: "Pani Puri",
    price: 99,
    discountPrice: 79,
    description: "Crispy puris filled with tangy and spicy water.",
    ratings: 4.3,
    ratingsCount: 180,
    type: "veg",
    cuisines: ["Indian", "Street Food"],
    category: "Fast Food",
  },
  {
    id: 4,
    name: "Hakka Noodles",
    price: 199,
    discountPrice: 169,
    description: "Stir-fried noodles with vegetables and Chinese sauces.",
    ratings: 4.4,
    ratingsCount: 150,
    type: "veg",
    cuisines: ["Chinese"],
    category: "Chinese",
  },
  {
    id: 5,
    name: "Chicken Lollipop",
    price: 249,
    discountPrice: 219,
    description: "Spicy and crispy fried chicken wings.",
    ratings: 4.6,
    ratingsCount: 90,
    type: "non-veg",
    cuisines: ["Chinese", "Fast Food"],
    category: "Chinese",
  },
  {
    id: 6,
    name: "Masala Dosa",
    price: 149,
    discountPrice: 129,
    description: "Crispy dosa stuffed with spicy potato filling.",
    ratings: 4.5,
    ratingsCount: 170,
    type: "veg",
    cuisines: ["South Indian"],
    category: "South Indian",
  },
  {
    id: 7,
    name: "Veg Manchurian",
    price: 179,
    discountPrice: 149,
    description: "Deep-fried veggie balls tossed in spicy Chinese sauce.",
    ratings: 4.3,
    ratingsCount: 140,
    type: "veg",
    cuisines: ["Chinese"],
    category: "Chinese",
  },
  {
    id: 8,
    name: "Cold Coffee",
    price: 129,
    discountPrice: 99,
    description: "Chilled coffee blended with ice and chocolate.",
    ratings: 4.2,
    ratingsCount: 110,
    type: "veg",
    cuisines: ["Beverages"],
    category: "Cool Drinks",
  },
  {
    id: 9,
    name: "Butter Chicken",
    price: 399,
    discountPrice: 349,
    description: "Creamy butter chicken served with naan or rice.",
    ratings: 4.8,
    ratingsCount: 250,
    type: "non-veg",
    cuisines: ["North Indian", "Mughlai"],
    category: "South Indian",
  },
  {
    id: 10,
    name: "Mango Shake",
    price: 119,
    discountPrice: 89,
    description: "Refreshing mango shake with fresh mango pulp.",
    ratings: 4.5,
    ratingsCount: 130,
    type: "veg",
    cuisines: ["Beverages"],
    category: "Cool Drinks",
  },
];

export default foodItems;
